origin/about modal
yanrzv/group-9 pull request #10
Opened 2022-12-24 16:04 UTC by TyllerDurden97

2022-12-25 01:35 UTC, yanrzv commented on src/partials/modal-read-more.html
> +      <use href="./images/sprite.svg#modal-close"></use>
Все кльово, тільки якогось ховера не вистачає на хресті

2022-12-25 01:36 UTC, yanrzv requested changes
Все кльово, тільки якогось ховера не вистачає на хресті. Закидуй секцію і будемо пробувати мержити разом з модалкою в меін

2022-12-25 11:51 UTC, TyllerDurden97 commented on src/partials/modal-read-more.html
> +      <use href="./images/sprite.svg#modal-close"></use>
По макету не знайшов ховер/фокус на кнопці закривання вікна. Якщо ми будемо самі додавати його, то треба ж щоб у всіх він був однаковим. Якщо ніхто ще не робив, я можу зробити. Пропоную робити таким самим кольором, як і всі інші кнопки та посилання макету при ховері.

2022-12-25 14:13 UTC, TyllerDurden97 commented
зробив ховер і фокус. Запушив

2022-12-26 01:40 UTC, yanrzv approved these changes

2022-12-26 01:40 UTC, merged