Add products section
yanrzv/group-9 pull request #5
Opened 2022-12-24 05:23 UTC by OIgaB

У секції Products зображення згідно з ТЗ є декоративними (не контентними) і додаються псевдо-елементами. Використала ::before для картинок i ::after для фону під картинками (у формі кружечків). Абсолютно позиціонувала їх відносно їх похідного елемента <li>. Псевдоелементу ::before довелось дати z-index: 1, оскільки ::after перекривав його. Застосувала цей варіант, бо не хотілося вантажити фон як зображення, щоб не був важкий сайт. Пробувала застосовувати альтернативний варіант з багатошаровим пирогом із фонових зображень (картинка і фон-градієнт) зі збірною властивістю background-position (коли перераховуються розташування усіх шарів через кому) - не спрацювало. Мабуть це тільки для зображень, до яких фон - градієнт не відноситься. Object-position, який згадував Іван на лекції, навіть не пробувала застосовувати, оскільки в конспекті вказано, що це виключно для контентних зображень. Мабуть це складно дивитися чужий код і здогадуватися, що вдарило тій людині по голові, що вона написала саме так)))

2022-12-25 00:24 UTC, yanrzv commented on src/sass/layouts/_products.scss
> +.products-btn {
Треба ховер і фокус

2022-12-25 00:32 UTC, yanrzv commented on src/sass/layouts/_products.scss
> +    &__item:first-child {
![image](https://user-images.githubusercontent.com/116461898/209453976-93267a07-28ae-4bca-824e-0f7bd5f85f03.png)

може подивись як виглядатиме коли до 767 не було фіксованої висоти? ну тіпа якісь там верхні і нижні падінги і шоб обмежувалось контентом, а то багато пустого місця на мобілках

2022-12-25 00:38 UTC, yanrzv reviewed
Взагалі все круто, код добре структуровано і було зручно його дивитись. Довше шукав до чого доїбатись, ніж розбирався в коді))

2022-12-25 00:40 UTC, yanrzv requested changes
Статус

2022-12-26 00:45 UTC, yanrzv approved these changes

2022-12-26 00:45 UTC, merged

2022-12-27 00:41 UTC, OIgaB commented on src/sass/layouts/_products.scss
> +.products-btn {
Зроблено!

2022-12-27 00:46 UTC, OIgaB commented on src/sass/layouts/_products.scss
> +    &__item:first-child {
Я зрозуміла, що ти маєш на увазі, зараз підлампічу

2022-12-27 00:48 UTC, OIgaB commented
> Взагалі все круто, код добре структуровано і було зручно його дивитись. Довше шукав до чого доїбатись, ніж розбирався в коді))

Ггг дякую!